# Generated by Django 4.0.5 on 2023-07-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reciever_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('destinations', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('On Hub', 'On Hub'), ('On Ride', 'On Ride'), ('Delivered', 'Delivered')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Due', 'Due'), ('Completed', 'Completed')], max_length=20)),
                ('recieve_amount', models.IntegerField()),
                ('assigned_deliveryman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dswiftweb.deliverycharges')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dswiftweb.unit')),
            ],
            options={
                'verbose_name': 'Delivery Item',
            },
        ),
        migrations.AddField(
            model_name='deliverycharges',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dswiftweb.unit'),
        ),
    ]
