# Generated by Django 4.0.5 on 2023-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dswiftweb', '0002_alter_deliveryitems_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitems',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
