# Generated by Django 4.0.5 on 2023-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dswiftweb', '0003_alter_deliveryitems_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitems',
            name='status',
            field=models.CharField(choices=[('Pending', 'On Hub'), ('On The Way', 'On Ride'), ('Confirmed', 'Delivered'), ('Returned', 'Returned')], max_length=20),
        ),
    ]
